### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by sdellis** [edsilv/manifesto-express-demo#1]
Just testing this out... and this is likely "user error" rather than anything wrong with the code.  I'm using Node.js v0.11.12 and recent versions of Chrome/FF.  However, I get the following when I start up the server.  Any thoughts?

```
ReferenceError: Promise is not defined
   at Function.Utils.loadManifest (/Users/shaune/Development/manifesto-express-demo/node_modules/manifesto/dist/server/manifesto.js:1042:24)
   at Object.module.exports.loadManifest (/Users/shaune/Development/manifesto-express-demo/node_modules/manifesto/dist/server/manifesto.js:1192:32)
   at /Users/shaune/Development/manifesto-express-demo/app.js:7:15
   at Layer.handle [as handle_request] (/Users/shaune/Development/manifesto-express-demo/node_modules/express/lib/router/layer.js:95:5)
   at next (/Users/shaune/Development/manifesto-express-demo/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/Users/shaune/Development/manifesto-express-demo/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/Users/shaune/Development/manifesto-express-demo/node_modules/express/lib/router/layer.js:95:5)
   at /Users/shaune/Development/manifesto-express-demo/node_modules/express/lib/router/index.js:277:22
   at Function.process_params (/Users/shaune/Development/manifesto-express-demo/node_modules/express/lib/router/index.js:330:12)
   at next (/Users/shaune/Development/manifesto-express-demo/node_modules/express/lib/router/index.js:271:10)
```

**Comment by edsilv** [comment]
Hey,

I've set up a Digital Ocean Ubuntu 14.04 x64 droplet running node v0.11.12 (using NVM). This has pod (https://github.com/yyx990803/pod) running a remote with a webhook to manifesto-express-demo.

http://188.226.180.21:3000/

Seems to be working ok.

http://stackoverflow.com/questions/21564993/native-support-for-promises-in-node-js

"v0.11.13 and later with the --harmony flag does have Promise". 

Odd given that I'm not seeing an error.

@demiankatz had a similar problem with the main Manifesto library. After installing NVM and the latest version of node it went away. Perhaps worth a try?
